<?php

use App\Http\Controllers\Admin\AdminAuditLogController;
use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\Admin\BankIntegrationController;
use App\Http\Controllers\Admin\BankIntegrationTestController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\CustomerWalletAdjustmentController;
use App\Http\Controllers\Admin\InvoiceController as AdminInvoiceController;
use App\Http\Controllers\Admin\NotificationEventController;
use App\Http\Controllers\Admin\NotificationEventRetryController;
use App\Http\Controllers\Admin\NotificationTemplateController;
use App\Http\Controllers\Admin\OpsAlertEventAcknowledgeController;
use App\Http\Controllers\Admin\OpsAlertEventController;
use App\Http\Controllers\Admin\OpsAlertEventResolveController;
use App\Http\Controllers\Admin\OpsAlertRuleController;
use App\Http\Controllers\Admin\OpsHealthController;
use App\Http\Controllers\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Admin\PaymentEventController;
use App\Http\Controllers\Admin\PaymentEventReconciliationController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ProviderActionJobController;
use App\Http\Controllers\Admin\ProviderActionJobRetryController;
use App\Http\Controllers\Admin\ProvisioningJobController;
use App\Http\Controllers\Admin\ProvisioningJobRetryController;
use App\Http\Controllers\Admin\ProvisioningProviderAccountController;
use App\Http\Controllers\Admin\ProvisioningProviderAccountTestController;
use App\Http\Controllers\Admin\ScheduledTaskRunController;
use App\Http\Controllers\Admin\ServiceController as AdminServiceController;
use App\Http\Controllers\Admin\ServiceProviderCancelController;
use App\Http\Controllers\Admin\ServiceProviderSyncController;
use App\Http\Controllers\Admin\ServiceRefundCreditController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\BankWebhookSandboxController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Internal\ProvisioningJobExecutionController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\NotificationPreferenceController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductCatalogController;
use App\Http\Controllers\ProductOrderController;
use App\Http\Controllers\ProviderCallbackController;
use App\Http\Controllers\ServiceCancellationController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\ServiceRenewalController;
use App\Http\Controllers\WalletController;
use App\Http\Controllers\WalletTopUpController;
use Illuminate\Foundation\Http\Middleware\ValidateCsrfToken;
use Illuminate\Support\Facades\Route;

Route::get('/', fn () => redirect('/products'));
Route::get('/products', ProductCatalogController::class)->name('products.index');
Route::post('/webhooks/bank/sandbox', BankWebhookSandboxController::class)->name('webhooks.bank-sandbox');
Route::post('/webhooks/providers/{provisioningProviderAccount}', ProviderCallbackController::class)->name('webhooks.providers');
Route::post('/internal/provisioning/jobs/{job}/execute', ProvisioningJobExecutionController::class)
    ->withoutMiddleware([ValidateCsrfToken::class])
    ->name('internal.provisioning-jobs.execute');

Route::middleware('guest')->group(function (): void {
    Route::get('/register', [RegisteredUserController::class, 'create'])->name('register');
    Route::post('/register', [RegisteredUserController::class, 'store']);
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store']);
});

Route::middleware('auth')->group(function (): void {
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/wallet', WalletController::class)->name('wallet.show');
    Route::get('/wallet/top-ups', [WalletTopUpController::class, 'index'])->name('wallet.top-ups.index');
    Route::post('/wallet/top-ups', [WalletTopUpController::class, 'store'])->name('wallet.top-ups.store');
    Route::get('/wallet/top-ups/{paymentIntent}', [WalletTopUpController::class, 'show'])->name('wallet.top-ups.show');
    Route::get('/invoices', [InvoiceController::class, 'index'])->name('invoices.index');
    Route::get('/invoices/{invoice}', [InvoiceController::class, 'show'])->name('invoices.show');
    Route::post('/invoices/{invoice}/pay', [InvoiceController::class, 'pay'])->name('invoices.pay');
    Route::post('/products/{product}/order', [ProductOrderController::class, 'store'])->name('products.order');
    Route::get('/orders', [OrderController::class, 'index'])->name('orders.index');
    Route::get('/orders/{order}', [OrderController::class, 'show'])->name('orders.show');
    Route::get('/services', [ServiceController::class, 'index'])->name('services.index');
    Route::get('/services/{service}', [ServiceController::class, 'show'])->name('services.show');
    Route::post('/services/{service}/renew', ServiceRenewalController::class)->name('services.renew');
    Route::post('/services/{service}/cancel', ServiceCancellationController::class)->name('services.cancel');
    Route::get('/notification-preferences', [NotificationPreferenceController::class, 'edit'])->name('notification-preferences.edit');
    Route::post('/notification-preferences', [NotificationPreferenceController::class, 'update'])->name('notification-preferences.update');

    Route::middleware('permission:admin.access')->prefix('admin')->name('admin.')->group(function (): void {
        Route::get('/', AdminDashboardController::class)->name('dashboard');
        Route::get('/audit-logs', [AdminAuditLogController::class, 'index'])->middleware('permission:audit_logs.view')->name('audit-logs.index');
        Route::get('/audit-logs/{adminAuditLog}', [AdminAuditLogController::class, 'show'])->middleware('permission:audit_logs.view')->name('audit-logs.show');
        Route::get('/products', [ProductController::class, 'index'])->middleware('permission:products.view')->name('products.index');
        Route::get('/products/create', [ProductController::class, 'create'])->middleware('permission:products.create')->name('products.create');
        Route::post('/products', [ProductController::class, 'store'])->middleware('permission:products.create')->name('products.store');
        Route::get('/products/{product}/edit', [ProductController::class, 'edit'])->middleware('permission:products.update')->name('products.edit');
        Route::put('/products/{product}', [ProductController::class, 'update'])->middleware('permission:products.update')->name('products.update');
        Route::delete('/products/{product}', [ProductController::class, 'destroy'])->middleware('permission:products.delete')->name('products.destroy');
        Route::get('/invoices', [AdminInvoiceController::class, 'index'])->middleware('permission:invoices.view')->name('invoices.index');
        Route::post('/invoices', [AdminInvoiceController::class, 'store'])->middleware('permission:invoices.create')->name('invoices.store');
        Route::get('/invoices/{invoice}', [AdminInvoiceController::class, 'show'])->middleware('permission:invoices.view')->name('invoices.show');
        Route::get('/payment-events', [PaymentEventController::class, 'index'])->middleware('permission:payment_events.view')->name('payment-events.index');
        Route::get('/payment-events/{paymentEvent}', [PaymentEventController::class, 'show'])->middleware('permission:payment_events.view')->name('payment-events.show');
        Route::post('/payment-events/{paymentEvent}/reconcile-wallet', PaymentEventReconciliationController::class)->middleware('permission:wallets.adjust')->name('payment-events.reconcile-wallet');
        Route::get('/customers', [CustomerController::class, 'index'])->middleware('permission:customers.view')->name('customers.index');
        Route::get('/customers/{user}', [CustomerController::class, 'show'])->middleware('permission:customers.view')->name('customers.show');
        Route::post('/customers/{user}/wallet-adjustments', CustomerWalletAdjustmentController::class)->middleware('permission:wallets.adjust')->name('customers.wallet-adjustments.store');
        Route::get('/bank-integrations', [BankIntegrationController::class, 'index'])->middleware('permission:bank_integrations.manage')->name('bank-integrations.index');
        Route::get('/bank-integrations/create', [BankIntegrationController::class, 'create'])->middleware('permission:bank_integrations.manage')->name('bank-integrations.create');
        Route::post('/bank-integrations', [BankIntegrationController::class, 'store'])->middleware('permission:bank_integrations.manage')->name('bank-integrations.store');
        Route::get('/bank-integrations/{bankIntegration}/edit', [BankIntegrationController::class, 'edit'])->middleware('permission:bank_integrations.manage')->name('bank-integrations.edit');
        Route::put('/bank-integrations/{bankIntegration}', [BankIntegrationController::class, 'update'])->middleware('permission:bank_integrations.manage')->name('bank-integrations.update');
        Route::post('/bank-integrations/{bankIntegration}/test', BankIntegrationTestController::class)->middleware('permission:bank_integrations.manage')->name('bank-integrations.test');
        Route::get('/provisioning-provider-accounts', [ProvisioningProviderAccountController::class, 'index'])->middleware('permission:provisioning_provider_accounts.manage')->name('provisioning-provider-accounts.index');
        Route::get('/provisioning-provider-accounts/create', [ProvisioningProviderAccountController::class, 'create'])->middleware('permission:provisioning_provider_accounts.manage')->name('provisioning-provider-accounts.create');
        Route::post('/provisioning-provider-accounts', [ProvisioningProviderAccountController::class, 'store'])->middleware('permission:provisioning_provider_accounts.manage')->name('provisioning-provider-accounts.store');
        Route::get('/provisioning-provider-accounts/{provisioningProviderAccount}/edit', [ProvisioningProviderAccountController::class, 'edit'])->middleware('permission:provisioning_provider_accounts.manage')->name('provisioning-provider-accounts.edit');
        Route::put('/provisioning-provider-accounts/{provisioningProviderAccount}', [ProvisioningProviderAccountController::class, 'update'])->middleware('permission:provisioning_provider_accounts.manage')->name('provisioning-provider-accounts.update');
        Route::post('/provisioning-provider-accounts/{provisioningProviderAccount}/test', ProvisioningProviderAccountTestController::class)->middleware('permission:provisioning_provider_accounts.manage')->name('provisioning-provider-accounts.test');
        Route::get('/orders', [AdminOrderController::class, 'index'])->middleware('permission:orders.view')->name('orders.index');
        Route::get('/orders/{order}', [AdminOrderController::class, 'show'])->middleware('permission:orders.view')->name('orders.show');
        Route::get('/services', [AdminServiceController::class, 'index'])->middleware('permission:services.view')->name('services.index');
        Route::get('/services/{service}', [AdminServiceController::class, 'show'])->middleware('permission:services.view')->name('services.show');
        Route::post('/services/{service}/refund-credit', ServiceRefundCreditController::class)->middleware('permission:wallets.adjust')->name('services.refund-credit');
        Route::post('/services/{service}/sync-provider', ServiceProviderSyncController::class)->middleware('permission:services.view')->name('services.sync-provider');
        Route::post('/services/{service}/cancel-provider', ServiceProviderCancelController::class)->middleware('permission:services.view')->name('services.cancel-provider');
        Route::get('/provider-action-jobs', [ProviderActionJobController::class, 'index'])->middleware('permission:provisioning_jobs.view')->name('provider-action-jobs.index');
        Route::post('/provider-action-jobs/{providerActionJob}/retry', ProviderActionJobRetryController::class)->middleware('permission:provisioning_jobs.view')->name('provider-action-jobs.retry');
        Route::get('/notification-events', [NotificationEventController::class, 'index'])->middleware('permission:notifications.manage')->name('notification-events.index');
        Route::get('/notification-events/{notificationEvent}', [NotificationEventController::class, 'show'])->middleware('permission:notifications.manage')->name('notification-events.show');
        Route::post('/notification-events/{notificationEvent}/retry', NotificationEventRetryController::class)->middleware('permission:notifications.manage')->name('notification-events.retry');
        Route::get('/notification-templates', [NotificationTemplateController::class, 'index'])->middleware('permission:notifications.manage')->name('notification-templates.index');
        Route::get('/notification-templates/{notificationTemplate}/edit', [NotificationTemplateController::class, 'edit'])->middleware('permission:notifications.manage')->name('notification-templates.edit');
        Route::put('/notification-templates/{notificationTemplate}', [NotificationTemplateController::class, 'update'])->middleware('permission:notifications.manage')->name('notification-templates.update');
        Route::get('/ops-health', OpsHealthController::class)->middleware('permission:provisioning_jobs.view')->name('ops-health');
        Route::get('/scheduled-task-runs', [ScheduledTaskRunController::class, 'index'])->middleware('permission:provisioning_jobs.view')->name('scheduled-task-runs.index');
        Route::get('/scheduled-task-runs/{scheduledTaskRun}', [ScheduledTaskRunController::class, 'show'])->middleware('permission:provisioning_jobs.view')->name('scheduled-task-runs.show');
        Route::get('/ops-alert-rules', [OpsAlertRuleController::class, 'index'])->middleware('permission:provisioning_jobs.view')->name('ops-alert-rules.index');
        Route::post('/ops-alert-rules', [OpsAlertRuleController::class, 'store'])->middleware('permission:provisioning_jobs.view')->name('ops-alert-rules.store');
        Route::put('/ops-alert-rules/{opsAlertRule}', [OpsAlertRuleController::class, 'update'])->middleware('permission:provisioning_jobs.view')->name('ops-alert-rules.update');
        Route::get('/ops-alert-events', [OpsAlertEventController::class, 'index'])->middleware('permission:provisioning_jobs.view')->name('ops-alert-events.index');
        Route::get('/ops-alert-events/{opsAlertEvent}', [OpsAlertEventController::class, 'show'])->middleware('permission:provisioning_jobs.view')->name('ops-alert-events.show');
        Route::post('/ops-alert-events/{opsAlertEvent}/acknowledge', OpsAlertEventAcknowledgeController::class)->middleware('permission:provisioning_jobs.view')->name('ops-alert-events.acknowledge');
        Route::post('/ops-alert-events/{opsAlertEvent}/resolve', OpsAlertEventResolveController::class)->middleware('permission:provisioning_jobs.view')->name('ops-alert-events.resolve');
        Route::get('/provisioning-jobs', [ProvisioningJobController::class, 'index'])->middleware('permission:provisioning_jobs.view')->name('provisioning-jobs.index');
        Route::get('/provisioning-jobs/{provisioningJob}', [ProvisioningJobController::class, 'show'])->middleware('permission:provisioning_jobs.view')->name('provisioning-jobs.show');
        Route::post('/provisioning-jobs/{provisioningJob}/retry', ProvisioningJobRetryController::class)->middleware('permission:provisioning_jobs.view')->name('provisioning-jobs.retry');
    });
});
